---
title: "Case Study 2 Sandbox"
format: html
---

## Case Study 2 Sandbox

```{r setup}
pacman::p_load(tidyverse, e1071, here, readxl, skimr, corrplot, patchwork)

raw_train <- read_xlsx(here('Case Study 2', 'BBBC-Train.xlsx'))
raw_test <- read_xlsx(here('Case Study 2', 'BBBC-Test.xlsx'))
```

```{r}
str(raw_train)
```
```{r}
anyNA(raw_train)
```

```{r}
skim(raw_train)
```

```{r}
train1 <- raw_train %>% 
  select(-Observation) %>% 
  mutate(
    Choice = as.factor(Choice),
    Gender = as.factor(Gender)
    )
test1 <- raw_test %>% 
  select(-Observation) %>%
  mutate(
    Choice = as.factor(Choice),
    Gender = as.factor(Gender)
    )

combined <- rbind(train1, test1)
```

```{r}
combined %>% select_if(is.numeric) %>% cor() %>% corrplot(method = 'number')
```

```{r}
combined %>% mutate(
  Gender = ifelse(Gender == 0, 'Female', 'Male'),
  Choice = ifelse(Choice == 0, 'Non-purchase', 'purchase')
  ) %>% 
  ggplot(aes(x = Gender, fill = Choice)) +
  geom_bar() + ggtitle('Gender vs Purchase')
```

```{r}
combox <- lapply(colnames(select_if(combined, is.numeric)),
       function(col) {
        ggplot(combined,
                aes(y = .data[[col]], x = .data$Choice)) + geom_boxplot() + ggtitle(col)
       }
)

combox[[1]] + combox[[2]] + combox[[3]]
combox[[4]] + combox[[5]] + combox[[6]]
combox[[7]] + combox[[8]] + combox[[9]]
```

```{r}
combined %>% group_by(Choice, P_Art) %>% 
  summarize(cnt = n()) %>% pivot_wider(id_cols = P_Art, names_from = Choice, values_from = cnt)
```




```{r}
set.seed(321)
form1 <- Choice ~ .
svmtune <- tune.svm(form1, data = train1, gamma = seq(.01,.1, by = .01), cost = seq(.1, 1, by = .1))
```

```{r}
svmtune$best.parameters

#best parameters: gamma 0.02, cost 0.5
```



Question for Dr. Roy
Clarity on word problem, 45%? 
15 + 45% of $15, cost to send out mailer to everyone vs cost to send out to those we predict would purchase. Consider False Positives

Subtract 1 from P_Art since Art history book would be included?
doesn't work, see contingency table

Append Data frames for visualizations?
Yes, done

Do we need to balance SVM dataset?
